/*
 * additem.java
 *
 * Created on April 26, 2013, 7:16 PM
 */
package BMS;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author  Owner
 */
public class additem extends javax.swing.JFrame {

    /** Creates new form additem */
    public additem() {
        initComponents();
        autonumber();
        setname();
    }

    void autonumber() {
        try {
            Connection k = DB.createConnection();
            ResultSet r = k.createStatement().executeQuery("select itemid from item");
            boolean b = false;
            int id = 0, max = 0;
            while (r.next()) {
                b = true;
                id = Integer.parseInt(r.getString("itemid"));
                if (max < id) {
                    max = id;
                }
            }
            if (b) {
                jTextField1.setText(max + 1 + "");
            } else {
                jTextField1.setText("1");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }


    }

    void setname() {
        try {
            Connection a = DB.createConnection();
            ResultSet r = a.createStatement().executeQuery("select * from item");
            Vector v = new Vector();

            while (r.next()) {
                String id = r.getString("itemid");
                String name = r.getString("itemname");
                String idname = id + " " + name;
                v.add(idname);
            }

            jList1.setListData(v);

        } catch (Exception e) {
            e.printStackTrace();
        }



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADD ITEM");
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Georgia", 3, 14));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Item Id       :-");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 100, 20);

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 14));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Item name :-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 110, 20);

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 14));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pup              :-");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 90, 110, 20);

        jLabel4.setFont(new java.awt.Font("Georgia", 3, 14));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sup              :-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 130, 100, 20);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Georgia", 3, 14));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(120, 10, 120, 23);

        jTextField2.setFont(new java.awt.Font("Georgia", 3, 14));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(120, 50, 120, 23);

        jTextField3.setFont(new java.awt.Font("Georgia", 3, 14));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(120, 90, 120, 23);

        jTextField4.setFont(new java.awt.Font("Georgia", 3, 14));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(120, 130, 120, 23);

        jLabel5.setFont(new java.awt.Font("Georgia", 3, 14));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Search     :-");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(260, 10, 90, 20);

        jTextField5.setFont(new java.awt.Font("Georgia", 3, 14));
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(360, 10, 110, 23);

        jList1.setFont(new java.awt.Font("Georgia", 3, 12));
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(310, 40, 160, 350);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Georgia", 3, 14));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 210, 100, 30);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Georgia", 3, 14));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 210, 100, 30);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Georgia", 3, 14));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(20, 280, 100, 30);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Georgia", 3, 14));
        jButton4.setText("Cancel");
        getContentPane().add(jButton4);
        jButton4.setBounds(170, 280, 100, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/abstract_0058_lightbox.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(-280, -140, 790, 560);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-486)/2, (screenSize.height-432)/2, 486, 432);
    }// </editor-fold>//GEN-END:initComponents
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Connection a = DB.createConnection();
            PreparedStatement p = a.prepareStatement("insert into item values('" + jTextField1.getText() + "','" + jTextField2.getText() + "','" + jTextField3.getText() + "','" + jTextField4.getText() + "')");
            p.executeUpdate();
            p.close();

            JOptionPane.showMessageDialog(null, "Successfully Saved");
            autonumber();
            setname();
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");


        } catch (Exception e) {
            e.printStackTrace();
        }


    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Connection a = DB.createConnection();
            PreparedStatement p = a.prepareStatement("update item set itemname='" + jTextField2.getText() + "', pup='" + jTextField3.getText() + "', sup='" + jTextField4.getText() + "' where itemid='" + jTextField1.getText() + "'");

            p.executeUpdate();
            p.close();

            JOptionPane.showMessageDialog(null, "Successfully Updated");

            autonumber();
            setname();
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");



        } catch (Exception e) {
            e.printStackTrace();
        }


    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        try {
            Connection a = DB.createConnection();
            ResultSet r = a.createStatement().executeQuery("select * from item where itemid='" + jTextField5.getText() + "'");
            boolean b = false;
            while (r.next()) {
                b = true;
                String a1 = r.getString("itemid");
                jTextField1.setText(a1);

                String a2 = r.getString("itemname");
                jTextField2.setText(a2);

                String a3 = r.getString("pup");
                jTextField3.setText(a3);
                String a4 = r.getString("sup");
                jTextField4.setText(a4);
            }
            if (!b) {
                autonumber();
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");

            }

        } catch (Exception e) {
            e.printStackTrace();
        }


    // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        try {
            Connection a = DB.createConnection();
            Object ob = jList1.getSelectedValue();
            String ab[] = ob.toString().split(" ");
            ResultSet r = a.createStatement().executeQuery("select * from item where itemid='" + ab[0] + "'  ");
            while (r.next()) {
                String a1 = r.getString("itemid");
                jTextField1.setText(a1);

                String a2 = r.getString("itemname");
                jTextField2.setText(a2);


                String a3 = r.getString("pup");
                jTextField3.setText(a3);

                String a4 = r.getString("sup");
                jTextField4.setText(a4);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    // TODO add your handling code here:
    }//GEN-LAST:event_jList1ValueChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Connection a = DB.createConnection();
            PreparedStatement p = a.prepareStatement("delete from item where itemid='" + jTextField1.getText() + "'");
            p.executeUpdate();
            p.close();

            JOptionPane.showMessageDialog(null, "Successfully Deleted");

            autonumber();
            setname();
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");

        } catch (Exception e) {
            e.printStackTrace();
        }


    // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new additem().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
