/*
 * stockout.java
 *
 * Created on May 7, 2013, 8:57 AM
 */
package BMS;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  Owner
 */
public class discount extends javax.swing.JFrame {

    /** Creates new form stockout */
    public discount() {
        initComponents();
        autonumber();
        setKey();
    }

    void autonumber() {
        try {
            Connection a = DB.createConnection();
            ResultSet r = a.createStatement().executeQuery("select invoiceno from stockout");

            boolean b = false;
            int invo = 0, max = 0;
            while (r.next()) {
                b = true;
                invo = Integer.parseInt(r.getString("invoiceno"));
            }

            if (b) {
                if (max <= invo) {
                    max = invo;
                }
                jTextField1.setText(max + 1 + "");

            } else {
                jTextField1.setText("1");
            }




        } catch (Exception e) {
            e.printStackTrace();
        }


    }
    
    void enterButton() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            Vector v = new Vector();
            v.add(jTextField2.getText());
            v.add(jTextField3.getText());
            v.add(jTextField4.getText());
            v.add(jTextField5.getText());
            v.add(jTextField6.getText());
            dtm.addRow(v);

            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            
            jTextField2.requestFocusInWindow();
            Object ob[] = new Object[5];
            int rowCount = dtm.getRowCount();
            double tot = 0.0;
            for (int a = 0; a < rowCount; a++) {
                for (int b = 0; b <= 4; b++) {
                    ob[b] = dtm.getValueAt(a, b);
                }
                tot += Double.parseDouble((String) ob[4]);
            }
            jTextField8.setText(tot + "");
            jTextField9.setText(tot + "");
        } catch (Exception e) {
            e.printStackTrace();
        }


    }
    
    void setKey() {
        JRootPane a = getRootPane();
        InputMap im = a.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap am = a.getActionMap();
        KeyStroke butenter = KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0);
        im.put(butenter, "butenter");
        am.put("butenter", new AbstractAction() {

        public void actionPerformed(ActionEvent e) {
                enterButton();
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("STOCKOUT");
        getContentPane().setLayout(null);

        dateChooserCombo1.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 14));
        getContentPane().add(dateChooserCombo1);
        dateChooserCombo1.setBounds(370, 0, 110, 20);

        jLabel7.setFont(new java.awt.Font("Georgia", 3, 14));
        jLabel7.setText("Grand Total :-");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(230, 400, 110, 20);

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 14));
        jLabel1.setText("Invoice no  :-");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 30, 110, 20);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(120, 30, 90, 20);

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 14));
        jLabel2.setText("    Item id  ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 90, 20);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(10, 80, 90, 20);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(110, 80, 90, 20);

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 14));
        jLabel3.setText("Item name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 60, 90, 20);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(210, 80, 90, 20);

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(310, 80, 90, 20);

        jLabel5.setFont(new java.awt.Font("Georgia", 3, 14));
        jLabel5.setText("       Sup     ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(210, 60, 90, 20);

        jLabel22.setFont(new java.awt.Font("Georgia", 3, 14));
        jLabel22.setText("       Qty");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(310, 60, 90, 20);

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(410, 80, 90, 20);

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField7KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(350, 430, 110, 20);

        jLabel21.setFont(new java.awt.Font("Georgia", 3, 14));
        jLabel21.setText("      Total  ");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(410, 60, 90, 20);

        jLabel20.setFont(new java.awt.Font("Georgia", 3, 14));
        jLabel20.setText("Cash              :-");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(230, 430, 110, 20);

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(350, 460, 110, 20);

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField9KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField9);
        jTextField9.setBounds(350, 400, 110, 20);

        jLabel6.setFont(new java.awt.Font("Georgia", 3, 14));
        jLabel6.setText("Balance        :-");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 460, 110, 20);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Georgia", 3, 14));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 400, 100, 30);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Georgia", 3, 14));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 440, 100, 30);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Georgia", 3, 14));
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 480, 100, 30);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "        Item Id", "     Item Name", "          Sup", "          Qty", "       Total"
            }
        ));
        jTable1.setInheritsPopupMenu(true);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 490, 280);

        jLabel23.setFont(new java.awt.Font("Georgia", 3, 14));
        jLabel23.setText("Employer :-");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(280, 30, 100, 20);

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField10KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField10);
        jTextField10.setBounds(380, 30, 120, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/aero_light_colors_4-wallpaper-1024x576.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-510, 0, 1020, 560);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-515)/2, (screenSize.height-557)/2, 515, 557);
    }// </editor-fold>//GEN-END:initComponents
    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        try {
            Connection a = DB.createConnection();
            ResultSet r = a.createStatement().executeQuery("select * from item where itemid='" + jTextField2.getText() + "'");

            boolean b = false;
            while (r.next()) {
                b = true;
                String a1 = r.getString("itemid");
                jTextField2.setText(a1);

                String a2 = r.getString("itemname");
                jTextField3.setText(a2);

//                String a4 = r.getString("sup");
//                jTextField4.setText(a4);

            }
            if (!b) {
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        autonumber();
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");

    // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
// TODO add your handling code here:
    }//GEN-LAST:event_jTextField6KeyReleased

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
// TODO add your handling code here:
    }//GEN-LAST:event_jTextField8KeyReleased

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        try {

            double a = 0.0, b = 0.0;
            if (jTextField4.getText().isEmpty()) {
                a = 0.0;
            } else {
                a = Double.parseDouble(jTextField4.getText());
            }
            if (jTextField5.getText().isEmpty()) {
                b = 0.0;
            } else {
                b = Double.parseDouble(jTextField5.getText());
            }

            jTextField6.setText(a * b + "");

        } catch (Exception e) {
            e.printStackTrace();
        }



    // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jTextField9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyReleased
// TODO add your handling code here:
    }//GEN-LAST:event_jTextField9KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.removeRow(jTable1.getSelectedRow());

            Object ob[] = new Object[9];
            int rowCount = dtm.getRowCount();
            double tot = 0.0;
            for (int a = 0; a < rowCount; a++) {
                for (int b = 0; b <= 4; b++) {
                    ob[b] = dtm.getValueAt(a, b);
                }
                tot += Double.parseDouble((String) ob[4]);

            }
            jTextField8.setText(tot + "");
            jTextField9.setText(tot + "");
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Connection a=DB.createConnection();
            String a1 = dateChooserCombo1.getText();
            String b[] = a1.split("/");
            String realDate = b[2] + "-" + b[0] + "-" + b[1];
            
             DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            Object ob[] = new Object[5];
            int rawCount = dtm.getRowCount();
            String custermer_id = null;
            for (int a2 = 0; a2 < rawCount; a2++) {
                for (int b1 = 0; b1 <= 4; b1++) {
                    ob[b1] = dtm.getValueAt(a2, b1);
                }
                ResultSet r = a.createStatement().executeQuery("select qty from stock where itemid='" + ob[0] + "'");
                
                double stockqty=0;
                while (r.next()) {
                    stockqty =Double.parseDouble(r.getString("qty"));
                }
                double stockoutqty=Double.parseDouble(ob[3]+"");
                double newqty=stockqty-stockoutqty;
                
                PreparedStatement p=a.prepareStatement("insert into stockout values('"+jTextField1.getText()+"','"+ob[0]+"','"+ob[1]+"','"+ob[2]+"','"+ob[3]+"','"+ob[4]+"','"+realDate+"')");
                p.executeUpdate();
                p.close();
                
                PreparedStatement p1=a.prepareStatement("update stock set qty='"+newqty+"' where itemid='"+ob[0]+"'");
                p1.executeUpdate();;
                p1.close();
                
                PreparedStatement p2=a.prepareStatement("insert into discount values('"+jTextField10.getText()+"','"+jTextField1.getText()+"','"+ob[0]+"','"+ob[1]+"','"+ob[2]+"','"+ob[3]+"','"+ob[4]+"','"+realDate+"')");
                p2.executeUpdate();
                p2.close();
                
                
            }
            
            int i = dtm.getRowCount();

            while (i > 0) {
                dtm.removeRow(i - 1);
                i--;
            }
            autonumber();
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
        
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }

        
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10KeyReleased

    private void jTextField7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyReleased
        try {
            try {
                
                double a = 0.0, b = 0.0;
                if (jTextField9.getText().isEmpty()) {
                    a = 0.0;
                } else {
                    a = Double.parseDouble(jTextField9.getText());
                }
                if (jTextField7.getText().isEmpty()) {
                    b = 0.0;
                } else {
                    b = Double.parseDouble(jTextField7.getText());
                }
                
                jTextField8.setText(a - b + "");
                
            } catch (Exception e) {
                e.printStackTrace();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new discount().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
