/*
 * Edit.java
 *
 * Created on January 18, 2013, 10:45 PM
 */
package BMS;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author  Window 8 Ultimate
 */
public class Editusernameandpassword extends javax.swing.JFrame {

    /** Creates new form Edit */
    public Editusernameandpassword() {
        initComponents();
        jTextField1.setEnabled(false);
        jTextField2.setEnabled(false);
        jPasswordField1.setEnabled(false);

        jButton4.setEnabled(false);
        jButton6.setEnabled(false);

        jTextField3.setEnabled(false);
        jTextField4.setEnabled(false);
        jPasswordField3.setEnabled(false);
        jPasswordField4.setEnabled(false);
        jButton3.setEnabled(false);
        jButton5.setEnabled(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jPasswordField4 = new javax.swing.JPasswordField();
        jButton5 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField3 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jRadioButton1.setText("Change User Name");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(70, 10, 157, 25);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jRadioButton2.setText("Change Password");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(410, 10, 149, 25);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Current User Name:-");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 50, 150, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Current Password  :-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 150, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("New User Name      :-");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 130, 150, 17);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(180, 50, 120, 20);

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 12));
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(180, 90, 120, 21);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(180, 130, 120, 21);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("Current Password   :-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 90, 160, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setText("Current User Name :-");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 50, 160, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel6.setText("New Password         :-");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(350, 130, 160, 17);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 12));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(510, 50, 120, 21);

        jButton3.setFont(new java.awt.Font("Georgia", 3, 14));
        jButton3.setText("Change Password");
        getContentPane().add(jButton3);
        jButton3.setBounds(350, 200, 165, 25);

        jPasswordField3.setFont(new java.awt.Font("Tahoma", 1, 12));
        getContentPane().add(jPasswordField3);
        jPasswordField3.setBounds(510, 130, 120, 21);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel7.setText("Confirm Password   :-");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(350, 170, 160, 17);

        jPasswordField4.setFont(new java.awt.Font("Tahoma", 1, 12));
        getContentPane().add(jPasswordField4);
        jPasswordField4.setBounds(510, 170, 120, 21);

        jButton5.setFont(new java.awt.Font("Georgia", 3, 14));
        jButton5.setText("Clear");
        getContentPane().add(jButton5);
        jButton5.setBounds(550, 200, 71, 25);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 0, 2, 0);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(510, 90, 120, 21);

        jButton6.setFont(new java.awt.Font("Georgia", 3, 14));
        jButton6.setText("Clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(230, 200, 71, 25);

        jButton4.setFont(new java.awt.Font("Georgia", 3, 14));
        jButton4.setText("Change User Name");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(20, 200, 173, 25);

        jLabel8.setForeground(new java.awt.Color(255, 51, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 0, 0);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(320, 10, 2, 220);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/aero_light_colors_2-wallpaper-1024x576.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-20, -280, 770, 550);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-653)/2, (screenSize.height-268)/2, 653, 268);
    }// </editor-fold>//GEN-END:initComponents
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if (jRadioButton1.isSelected()) {
            jTextField1.setEnabled(true);
            jTextField2.setEnabled(true);
            jPasswordField1.setEnabled(true);

            jButton4.setEnabled(true);
            jButton6.setEnabled(true);

            jTextField3.setEnabled(false);
            jTextField4.setEnabled(false);
            jPasswordField3.setEnabled(false);
            jPasswordField4.setEnabled(false);
            jButton3.setEnabled(false);
            jButton5.setEnabled(false);
        } else {

        }


    // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if (jRadioButton2.isSelected()) {
            jTextField1.setEnabled(false);
            jTextField2.setEnabled(false);
            jPasswordField1.setEnabled(false);

            jButton4.setEnabled(false);
            jButton6.setEnabled(false);

            jTextField3.setEnabled(true);
            jTextField4.setEnabled(true);
            jPasswordField3.setEnabled(true);
            jPasswordField4.setEnabled(true);
            jButton3.setEnabled(true);
            jButton5.setEnabled(true);
        } else {
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased




        try {
            Connection k = DB.createConnection();
            if (jTextField2.getText().isEmpty()) {
                jButton4.setEnabled(false);//username aka empty wunoth save button inactive kireema
                jLabel5.setText("");
            } else {
                if (jTextField2.getText().length() >= 5) {//username length aka 5 characters limit karanna
                    jButton4.setEnabled(true);

                    boolean b = false;
                    ResultSet r = k.createStatement().executeQuery("select * from login where username='" + jTextField2.getText() + "'");
                    while (r.next()) { //r.next true wenne ape sql query aka true wunoth itm means username=jt1.gettext wunoth ...nathnm else
                        b = true;
                    }
                    if (b) {
                        jLabel8.setText("Username Allready Exist!");
                        jButton4.setEnabled(false);
                    } else {
                        jLabel8.setText("Available!");
                        jButton4.setEnabled(true);
                    }
                } else {
                    jLabel8.setText("Type more than 5 characters!");
                }

            }



        } catch (Exception e) {
            e.printStackTrace();
        }






// TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            Connection k = DB.createConnection();
            ResultSet r = k.createStatement().executeQuery("select * from login where username='" + jTextField1.getText() + "'and password='" + jPasswordField1.getText() + "'");
            boolean b = false;
            while (r.next()) {
                b = true;
            }
            if (b) {
                PreparedStatement p = k.prepareStatement("update login set username='" + jTextField2.getText() + "' where username='" + jTextField1.getText() + "'");
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(null, "successfully updated");
                jTextField2.setText("");
                jTextField1.setText("");
                jPasswordField1.setText("");
                 jLabel8.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "wrong username");
                jTextField2.setText("");
                 jLabel8.setText("");
            }



        } catch (Exception e) {
            e.printStackTrace();
        }





    // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        jTextField2.setText("");
        jTextField1.setText("");
        jPasswordField1.setText("");
        jLabel8.setText("");
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Editusernameandpassword().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
