/*
 * login.java
 *
 * Created on April 22, 2013, 7:28 PM
 */

package BMS;


import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author  Owner
 */
public class login extends javax.swing.JFrame {
    static String displayuser;
    
    /** Creates new form login */
    public login() {
        initComponents();
        jButton1.setEnabled(false);
        rootPane.setDefaultButton(jButton1);
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 18));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User name :-");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 130, 21);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Georgia", 3, 18));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password   :-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 130, 21);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(150, 10, 130, 23);

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(150, 60, 130, 23);

        jButton1.setFont(new java.awt.Font("Georgia", 3, 14));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 120, 75, 25);

        jButton2.setFont(new java.awt.Font("Georgia", 3, 14));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 120, 83, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Colour Background 613 1248360959.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-1480, -930, 1950, 1420);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-299)/2, (screenSize.height-198)/2, 299, 198);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        try {
            if(jTextField1.getText().isEmpty()){
            jButton1.setEnabled(false);
            }
            
            if(jPasswordField1.getText().isEmpty()){
            jButton1.setEnabled(false);
            
            }
            if(!jTextField1.getText().isEmpty() && !jPasswordField1.getText().isEmpty()){
            jButton1.setEnabled(true);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }

        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
try {
            if(jTextField1.getText().isEmpty()){
            jButton1.setEnabled(false);
            }
            
            if(jPasswordField1.getText().isEmpty()){
            jButton1.setEnabled(false);
            
            }
            if(!jTextField1.getText().isEmpty() && !jPasswordField1.getText().isEmpty()){
            jButton1.setEnabled(true);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        displayuser=jTextField1.getText();
        try {
            Connection a=DB.createConnection();
            ResultSet r=a.createStatement().executeQuery("select * from login where username='"+jTextField1.getText()+"' and password='"+jPasswordField1.getText()+"'");
            
            boolean b=false;
            while(r.next()){
            b=true;
            }
            if(b){
            this.dispose();
            new mainboard().setVisible(true);
                
            }
            else{
            JOptionPane.showMessageDialog(null, "Wrong Username or Password");
            jTextField1.setText("");
            jPasswordField1.setText("");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }

        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//               
                new login().setVisible(true);
                
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
