/*
 * monthlyreport.java
 *
 * Created on May 19, 2013, 8:38 AM
 */
package BMS;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author  Owner
 */
public class monthlyreport extends javax.swing.JFrame {

    /** Creates new form monthlyreport */
    public monthlyreport() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MONTHLY REPORT");
        getContentPane().setLayout(null);

        dateChooserCombo1.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 12));
        getContentPane().add(dateChooserCombo1);
        dateChooserCombo1.setBounds(40, 10, 120, 20);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(240, 10, 100, 20);

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel2.setText("Bank Charges                     :-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 250, 160, 20);

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 11));
        jLabel3.setText("     Income");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 40, 80, 20);

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel4.setText("Card game Income                                   :-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 200, 230, 20);

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel5.setText("Guest Fees received                                 :-");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 180, 230, 20);

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel6.setText("Other Income(Club Night)                    :-");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 160, 230, 20);

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel7.setText("Interest from Savings Account            :-");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 140, 230, 20);

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel8.setText("Interest from Fixed deposit                    :-");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 120, 230, 20);

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel9.setText("Profit from Liquor trading amount     :-");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 100, 230, 20);

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel10.setText("Revenue from billiard room                  :-");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 80, 230, 20);

        jLabel11.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel11.setText("Electricity Charges               :-");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(310, 250, 170, 20);

        jLabel12.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel12.setText("Postage & Stamps               :-");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 390, 160, 20);

        jLabel13.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel13.setText("Subscription received from members:-");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 60, 230, 20);

        jLabel14.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel14.setText("Night Club Expences         :-");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 310, 160, 20);

        jLabel15.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel15.setText("Repairs & Maintenance    :-");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 290, 160, 20);

        jLabel16.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel16.setText("Printing & Stationary          :-");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(310, 270, 170, 20);

        jLabel17.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel17.setText("Miscellaneous expences       :-");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(310, 290, 170, 20);

        jLabel18.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel18.setText("Meeting Expences                  :-");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(310, 310, 170, 20);

        jLabel19.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel19.setText("Assessment Tax M.C             :-");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(310, 450, 180, 20);

        jLabel20.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel20.setText("Allowance paid to others :-");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(10, 270, 160, 20);

        jLabel21.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel21.setText("Sacurity Service Charges:-");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(10, 370, 160, 20);

        jLabel22.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel22.setText("Monthly Tax                       :-");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(10, 490, 160, 20);

        jLabel23.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel23.setText("Dialog TV Expences            :-");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(10, 350, 160, 20);

        jLabel24.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel24.setText("Water Bill                             :-");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(10, 330, 160, 20);

        jLabel25.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel25.setText("Audit Fees                                :-");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(310, 410, 180, 20);

        jLabel26.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel26.setText("Bottle,Store room Expences:-");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(310, 390, 180, 20);

        jLabel27.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel27.setText("Entertainment                       :-");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(310, 370, 180, 20);

        jLabel28.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel28.setText("Labour Wages                         :-");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(310, 350, 180, 20);

        jLabel29.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel29.setText("Telephone Expences              :-");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(310, 330, 170, 20);

        jLabel30.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel30.setText("Sport Expences                       :-");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(310, 430, 180, 20);

        jLabel31.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel31.setText("Clerical Charges                :-");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(10, 450, 160, 20);

        jLabel32.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel32.setText("Indoor games Expences    :-");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(10, 430, 160, 20);

        jLabel33.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel33.setText("Petty Cash                               :-");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(310, 470, 180, 20);

        jLabel34.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel34.setText("Club Maintenance             :-");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(10, 410, 160, 20);

        jLabel35.setFont(new java.awt.Font("Georgia", 0, 11));
        jLabel35.setText("Scavenging Charges        :-");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(10, 470, 160, 20);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField1.setText("0");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 60, 100, 21);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField2.setText("0");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(240, 80, 100, 21);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField3.setText("0");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(240, 100, 100, 21);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField4.setText("0");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(240, 120, 100, 21);

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField5.setText("0");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(240, 140, 100, 21);

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField6.setText("0");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(240, 160, 100, 21);

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField7.setText("0");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(240, 180, 100, 21);

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField8.setText("0");
        getContentPane().add(jTextField8);
        jTextField8.setBounds(240, 200, 100, 21);

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField9.setText("0");
        getContentPane().add(jTextField9);
        jTextField9.setBounds(180, 250, 110, 21);

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField10.setText("0");
        getContentPane().add(jTextField10);
        jTextField10.setBounds(490, 250, 110, 21);

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField11.setText("0");
        getContentPane().add(jTextField11);
        jTextField11.setBounds(180, 270, 110, 21);

        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField12.setText("0");
        getContentPane().add(jTextField12);
        jTextField12.setBounds(490, 270, 110, 21);

        jTextField13.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField13.setText("0");
        getContentPane().add(jTextField13);
        jTextField13.setBounds(180, 290, 110, 21);

        jTextField14.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField14.setText("0");
        getContentPane().add(jTextField14);
        jTextField14.setBounds(490, 290, 110, 21);

        jTextField15.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField15.setText("0");
        getContentPane().add(jTextField15);
        jTextField15.setBounds(180, 310, 110, 21);

        jTextField16.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField16.setText("0");
        getContentPane().add(jTextField16);
        jTextField16.setBounds(490, 310, 110, 21);

        jTextField17.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField17.setText("0");
        getContentPane().add(jTextField17);
        jTextField17.setBounds(180, 330, 110, 21);

        jTextField18.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField18.setText("0");
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField18);
        jTextField18.setBounds(490, 330, 110, 21);

        jTextField19.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField19.setText("0");
        getContentPane().add(jTextField19);
        jTextField19.setBounds(180, 350, 110, 21);

        jTextField20.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField20.setText("0");
        getContentPane().add(jTextField20);
        jTextField20.setBounds(490, 350, 110, 21);

        jTextField21.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField21.setText("0");
        getContentPane().add(jTextField21);
        jTextField21.setBounds(180, 370, 110, 21);

        jTextField22.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField22.setText("0");
        getContentPane().add(jTextField22);
        jTextField22.setBounds(490, 370, 110, 21);

        jTextField23.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField23.setText("0");
        getContentPane().add(jTextField23);
        jTextField23.setBounds(180, 390, 110, 21);

        jTextField24.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField24.setText("0");
        getContentPane().add(jTextField24);
        jTextField24.setBounds(490, 390, 110, 21);

        jTextField25.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField25.setText("0");
        getContentPane().add(jTextField25);
        jTextField25.setBounds(180, 410, 110, 21);

        jTextField26.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField26.setText("0");
        getContentPane().add(jTextField26);
        jTextField26.setBounds(490, 410, 110, 21);

        jTextField27.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField27.setText("0");
        getContentPane().add(jTextField27);
        jTextField27.setBounds(180, 430, 110, 21);

        jTextField28.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField28.setText("0");
        getContentPane().add(jTextField28);
        jTextField28.setBounds(490, 430, 110, 21);

        jTextField29.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField29.setText("0");
        getContentPane().add(jTextField29);
        jTextField29.setBounds(180, 450, 110, 21);

        jTextField30.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField30.setText("0");
        getContentPane().add(jTextField30);
        jTextField30.setBounds(490, 450, 110, 21);

        jTextField31.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField31.setText("0");
        getContentPane().add(jTextField31);
        jTextField31.setBounds(180, 470, 110, 21);

        jTextField32.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField32.setText("0");
        getContentPane().add(jTextField32);
        jTextField32.setBounds(490, 470, 110, 21);

        jTextField33.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField33.setText("0");
        jTextField33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField33ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField33);
        jTextField33.setBounds(180, 490, 110, 21);

        jButton1.setFont(new java.awt.Font("Georgia", 3, 14));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 530, 80, 30);

        jButton2.setFont(new java.awt.Font("Georgia", 3, 14));
        jButton2.setText("Monthly Report ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 530, 170, 30);

        jLabel36.setFont(new java.awt.Font("Georgia", 3, 11));
        jLabel36.setText("       Less: Expenditure");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(200, 230, 140, 20);

        jButton3.setFont(new java.awt.Font("Georgia", 3, 14));
        jButton3.setText("Clear Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(440, 530, 140, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/abstract-background-13.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-740, -10, 1510, 610);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-618)/2, (screenSize.height-613)/2, 618, 613);
    }// </editor-fold>//GEN-END:initComponents
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField33ActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_jTextField33ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String a1 = dateChooserCombo1.getText();
            String c[] = a1.split("/");
            String realDate = c[2] + "-" + c[0] + "-" + c[1];

            Connection a = DB.createConnection();
            ResultSet r = a.createStatement().executeQuery("select month from monthlyreport");

            boolean b = false;
            while (r.next()) {
                b = true;
            }
            ResultSet r1 = a.createStatement().executeQuery("select * from monthlyreport where month='" + jComboBox1.getSelectedItem() + "'");

            double b1 = 0.0, b2 = 0.0, b3 = 0.0, b4 = 0.0, b5 = 0.0, b6 = 0.0, b7 = 0.0, b8 = 0.0, b9 = 0.0, b10 = 0.0, b11 = 0.0, b12 = 0.0, b13 = 0.0, b14 = 0.0, b15 = 0.0, b16 = 0.0, b17 = 0.0, b18 = 0.0, b19 = 0.0, b20 = 0.0, b21 = 0.0, b22 = 0.0, b23 = 0.0, b24 = 0.0, b25 = 0.0, b26 = 0.0, b27 = 0.0, b28 = 0.0, b29 = 0.0, b30 = 0.0, b31 = 0.0, b32 = 0.0, b33 = 0.0;
            while (r1.next()) {
                b1 = Double.parseDouble(r1.getString("memberssubscription"));
                b2 = Double.parseDouble(r1.getString("billiardroom"));
                b3 = Double.parseDouble(r1.getString("fixeddepositinterest"));
                b4 = Double.parseDouble(r1.getString("savingsaccountinterest"));
                b5 = Double.parseDouble(r1.getString("savingsaccountinterest"));
                b6 = Double.parseDouble(r1.getString("guestfees"));
                b7 = Double.parseDouble(r1.getString("cardgame"));
                b8 = Double.parseDouble(r1.getString("bankdeposits"));
                b9 = Double.parseDouble(r1.getString("electricitychargers"));
                b10 = Double.parseDouble(r1.getString("paidallowance"));
                b11 = Double.parseDouble(r1.getString("printingstationary"));
                b12 = Double.parseDouble(r1.getString("repairmaintance"));
                b13 = Double.parseDouble(r1.getString("miscellaneousexpences"));
                b14 = Double.parseDouble(r1.getString("nightclubexpences"));
                b15 = Double.parseDouble(r1.getString("meetingexpences"));
                b16 = Double.parseDouble(r1.getString("waterbill"));
                b17 = Double.parseDouble(r1.getString("telephoneexpences"));
                b18 = Double.parseDouble(r1.getString("dialogtv"));
                b19 = Double.parseDouble(r1.getString("labourwages"));
                b20 = Double.parseDouble(r1.getString("securityservice"));
                b21 = Double.parseDouble(r1.getString("entertainment"));
                b22 = Double.parseDouble(r1.getString("postagestamps"));
                b23 = Double.parseDouble(r1.getString("emptybottlestoreroomexpences"));
                b24 = Double.parseDouble(r1.getString("clubmaintenance"));
                b25 = Double.parseDouble(r1.getString("auditfees"));
                b26 = Double.parseDouble(r1.getString("indoorgamesexpences"));
                b27 = Double.parseDouble(r1.getString("sportexpences"));
                b28 = Double.parseDouble(r1.getString("clericalcharges"));
                b29 = Double.parseDouble(r1.getString("assessmenttax"));
                b30 = Double.parseDouble(r1.getString("scavengingcharges"));
                b31 = Double.parseDouble(r1.getString("pettycash"));
                b32 = Double.parseDouble(r1.getString("profitfromliquor"));
                b33 = Double.parseDouble(r1.getString("monthlytax"));

            }
            double newmemberssubscription = b1 + Double.parseDouble(jTextField1.getText());
            double newbilliardroom = b2 + Double.parseDouble(jTextField2.getText());
            double newfixeddepositinterest = b3 + Double.parseDouble(jTextField4.getText());
            double newsavingsaccountinterest = b4 + Double.parseDouble(jTextField5.getText());
            double newclubnight = b5 + Double.parseDouble(jTextField6.getText());
            double newguestfees = b6 + Double.parseDouble(jTextField7.getText());
            double newcardgame = b7 + Double.parseDouble(jTextField8.getText());
            double newbankdeposits = b8 + Double.parseDouble(jTextField9.getText());
            double newelectricitychargers = b9 + Double.parseDouble(jTextField10.getText());
            double newpaidallowance = b10 + Double.parseDouble(jTextField11.getText());
            double newprintingstationary = b11 + Double.parseDouble(jTextField12.getText());
            double newrepairmaintance = b12 + Double.parseDouble(jTextField13.getText());
            double newmiscellaneousexpences = b13 + Double.parseDouble(jTextField14.getText());
            double newnightclubexpences = b14 + Double.parseDouble(jTextField15.getText());
            double newmeetingexpences = b15 + Double.parseDouble(jTextField16.getText());
            double newwaterbill = b16 + Double.parseDouble(jTextField17.getText());
            double newtelephoneexpences = b17 + Double.parseDouble(jTextField18.getText());
            double newdialogtv = b18 + Double.parseDouble(jTextField19.getText());
            double newlabourwages = b19 + Double.parseDouble(jTextField20.getText());
            double newsecurityservice = b20 + Double.parseDouble(jTextField21.getText());
            double newentertainment = b21 + Double.parseDouble(jTextField22.getText());
            double newpostagestamps = b22 + Double.parseDouble(jTextField23.getText());
            double newemptybottlestoreroomexpences = b23 + Double.parseDouble(jTextField24.getText());
            double newclubmaintenance = b24 + Double.parseDouble(jTextField25.getText());
            double newauditfees = b25 + Double.parseDouble(jTextField26.getText());
            double newindoorgamesexpences = b26 + Double.parseDouble(jTextField27.getText());
            double newsportexpences = b27 + Double.parseDouble(jTextField28.getText());
            double newclericalcharges = b28 + Double.parseDouble(jTextField29.getText());
            double newassessmenttax = b29 + Double.parseDouble(jTextField30.getText());
            double newscavengingcharges = b30 + Double.parseDouble(jTextField31.getText());
            double newpettycash = b31 + Double.parseDouble(jTextField32.getText());
            double newprofitfromliquor = b32 + Double.parseDouble(jTextField3.getText());
            double newmonthlytax = b33 + Double.parseDouble(jTextField33.getText());

            if (b) {
                PreparedStatement p1 = a.prepareStatement("update monthlyreport set memberssubscription='" + newmemberssubscription + "',billiardroom='" + newbilliardroom + "',profitfromliquor='" + newprofitfromliquor + "',fixeddepositinterest='" + newfixeddepositinterest + "',savingsaccountinterest='" + newsavingsaccountinterest + "',clubnight='" + newclubnight + "',guestfees='" + newguestfees + "',cardgame='" + newcardgame + "',bankdeposits='" + newbankdeposits + "',electricitychargers='" + newelectricitychargers + "',paidallowance='" + newpaidallowance + "',printingstationary='" + newprintingstationary + "',repairmaintance='" + newrepairmaintance + "',miscellaneousexpences='" + newmiscellaneousexpences + "',nightclubexpences='" + newnightclubexpences + "',meetingexpences='" + newmeetingexpences + "',waterbill='" + newwaterbill + "',telephoneexpences='" + newtelephoneexpences + "',dialogtv='" + newdialogtv + "',labourwages='" + newlabourwages + "',securityservice='" + newsecurityservice + "',entertainment='" + newentertainment + "',postagestamps='" + newpostagestamps + "',emptybottlestoreroomexpences='" + newemptybottlestoreroomexpences + "',clubmaintenance='" + newclubmaintenance + "',auditfees='" + newauditfees + "',indoorgamesexpences='" + newindoorgamesexpences + "',sportexpences='" + newsportexpences + "',clericalcharges='" + newclericalcharges + "',assessmenttax='" + newassessmenttax + "',scavengingcharges='" + newscavengingcharges + "',pettycash='" + newpettycash + "',regdate='" + realDate + "',monthlytax='"+newmonthlytax+"' where month='"+jComboBox1.getSelectedItem()+"'");
                p1.executeUpdate();
                p1.close();

            } else {
                PreparedStatement p2 = a.prepareStatement("insert into monthlyreport values('" + jComboBox1.getSelectedItem() + "','" + jTextField1.getText() + "','" + jTextField2.getText() + "','" + jTextField3.getText() + "','" + jTextField4.getText() + "','" + jTextField5.getText() + "','" + jTextField6.getText() + "','" + jTextField7.getText() + "','" + jTextField8.getText() + "','" + jTextField9.getText() + "','" + jTextField10.getText() + "','" + jTextField11.getText() + "','" + jTextField12.getText() + "','" + jTextField13.getText() + "','" + jTextField14.getText() + "','" + jTextField15.getText() + "','" + jTextField16.getText() + "','" + jTextField17.getText() + "','" + jTextField18.getText() + "','" + jTextField19.getText() + "','" + jTextField20.getText() + "','" + jTextField21.getText() + "','" + jTextField22.getText() + "','" + jTextField23.getText() + "','" + jTextField24.getText() + "','" + jTextField25.getText() + "','" + jTextField26.getText() + "','" + jTextField27.getText() + "','" + jTextField28.getText() + "','" + jTextField29.getText() + "','" + jTextField30.getText() + "','" + jTextField31.getText() + "','" + jTextField32.getText() + "','" + jTextField33.getText() + "','" + realDate + "')");

                p2.executeUpdate();
                p2.close();

            }
            JOptionPane.showMessageDialog(null, "Successfully Saved");
            jTextField1.setText("0");
            jTextField2.setText("0");
            jTextField3.setText("0");
            jTextField4.setText("0");
            jTextField5.setText("0");
            jTextField6.setText("0");
            jTextField7.setText("0");
            jTextField8.setText("0");
            jTextField9.setText("0");
            jTextField10.setText("0");
            jTextField11.setText("0");
            jTextField12.setText("0");
            jTextField13.setText("0");
            jTextField14.setText("0");
            jTextField15.setText("0");
            jTextField16.setText("0");
            jTextField17.setText("0");
            jTextField18.setText("0");
            jTextField19.setText("0");
            jTextField20.setText("0");
            jTextField21.setText("0");
            jTextField22.setText("0");
            jTextField23.setText("0");
            jTextField24.setText("0");
            jTextField25.setText("0");
            jTextField26.setText("0");
            jTextField27.setText("0");
            jTextField28.setText("0");
            jTextField29.setText("0");
            jTextField30.setText("0");
            jTextField31.setText("0");
            jTextField32.setText("0");
            jTextField33.setText("0");


        } catch (Exception e) {
            e.printStackTrace();
        }


    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Connection a = DB.createConnection();
            PreparedStatement p = a.prepareStatement("delete from monthlyreport where month='" + jComboBox1.getSelectedItem() + "'");
            p.executeUpdate();
            p.close();

            JOptionPane.showMessageDialog(null, "Successfully Deleted");

        } catch (Exception e) {
            e.printStackTrace();
        }


    // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String a = dateChooserCombo1.getText();
            String b[] = a.split("/");
            String realDate = b[2] + "-" + b[0] + "-" + b[1];

            String jasp = "Report/monthlyreport.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(jasp);
            Map<String, Object> params = new HashMap<String, Object>();

            params.put("Month1", jComboBox1.getSelectedItem());

            JasperPrint jp = JasperFillManager.fillReport(jr, params, DB.createConnection());
            JasperViewer jv = new JasperViewer(jp);
            JasperViewer.viewReport(jp, false);

            jTextField1.setText("0");
            jTextField2.setText("0");
            jTextField3.setText("0");
            jTextField4.setText("0");
            jTextField5.setText("0");
            jTextField6.setText("0");
            jTextField7.setText("0");
            jTextField8.setText("0");
            jTextField9.setText("0");
            jTextField10.setText("0");
            jTextField11.setText("0");
            jTextField12.setText("0");
            jTextField13.setText("0");
            jTextField14.setText("0");
            jTextField15.setText("0");
            jTextField16.setText("0");
            jTextField17.setText("0");
            jTextField18.setText("0");
            jTextField19.setText("0");
            jTextField20.setText("0");
            jTextField21.setText("0");
            jTextField22.setText("0");
            jTextField23.setText("0");
            jTextField24.setText("0");
            jTextField25.setText("0");
            jTextField26.setText("0");
            jTextField27.setText("0");
            jTextField28.setText("0");
            jTextField29.setText("0");
            jTextField30.setText("0");
            jTextField31.setText("0");
            jTextField32.setText("0");
            jTextField33.setText("0");

        } catch (Exception e) {
            e.printStackTrace();
        }


    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new monthlyreport().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
