/*
 * monthlyincomes.java
 *
 * Created on May 27, 2013, 9:00 PM
 */
package BMS;

import java.sql.Connection;
import java.sql.ResultSet;

/**
 *
 * @author  Owner
 */
public class monthlyincomes extends javax.swing.JFrame {

    /** Creates new form monthlyincomes */
    public monthlyincomes() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MONTHLY INCOMES");
        getContentPane().setLayout(null);

        jComboBox1.setFont(new java.awt.Font("Georgia", 1, 11));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(70, 10, 95, 20);

        jButton1.setFont(new java.awt.Font("Georgia", 1, 11));
        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 3, 100, 30);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 11));
        jLabel1.setText("Billiard room                                 :-");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 40, 210, 20);

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 11));
        jLabel2.setText("Interest from fixed deposit     :-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 210, 20);

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 11));
        jLabel3.setText("Interest from SavingAccount:-");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 100, 210, 20);

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 11));
        jLabel4.setText("Club night income                       :-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 130, 210, 20);

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 11));
        jLabel5.setText("Guest Fees                                        :-");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 160, 210, 20);

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 11));
        jLabel6.setText("Card Game Incomes                    :-");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 190, 210, 20);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(220, 40, 110, 21);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(220, 70, 110, 21);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(220, 100, 110, 21);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 12));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(220, 130, 110, 21);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 12));
        getContentPane().add(jTextField5);
        jTextField5.setBounds(220, 160, 110, 21);

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(220, 190, 110, 21);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-353)/2, (screenSize.height-270)/2, 353, 270);
    }// </editor-fold>//GEN-END:initComponents
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Connection a = DB.createConnection();
            ResultSet r = a.createStatement().executeQuery("select * from monthlyreport where month='" + jComboBox1.getSelectedItem() + "'");

            boolean b = false;
            while (r.next()) {
                b = true;
                String billiard = r.getString("billiardroom");
                jTextField1.setText(billiard);

                String fixeddeposit = r.getString("fixeddepositinterest");
                jTextField2.setText(fixeddeposit);

                String savings = r.getString("savingsaccountinterest");
                jTextField3.setText(savings);

                String clubnight = r.getString("clubnight");
                jTextField4.setText(clubnight);

                String guestfees = r.getString("guestfees");
                jTextField5.setText(guestfees);

                String cardgame = r.getString("cardgame");
                jTextField6.setText(cardgame);
            }
            if (!b) {
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }


    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new monthlyincomes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
