/*
 * stockin.java
 *
 * Created on April 26, 2013, 7:16 PM
 */
package BMS;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author  Owner
 */
public class stockin extends javax.swing.JFrame {

    /** Creates new form stockin */
    public stockin() {
        initComponents();
        setname();
    }

    void setname() {
        try {
            Connection a = DB.createConnection();
            ResultSet r = a.createStatement().executeQuery("select * from stock");
            Vector v = new Vector();

            while (r.next()) {
                String qty = r.getString("qty");
                String name = r.getString("itemname");
                String nameqty = name + "    " + qty;
                v.add(nameqty);
            }

            jList1.setListData(v);

        } catch (Exception e) {
            e.printStackTrace();
        }



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("STOCK IN");
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 14));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Item Id       :-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 110, 20);

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 14));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Search     :-");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 10, 90, 20);

        jLabel4.setFont(new java.awt.Font("Georgia", 3, 14));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pup              :-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 70, 110, 20);

        jLabel5.setFont(new java.awt.Font("Georgia", 3, 14));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sup               :-");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 100, 110, 20);

        jLabel6.setFont(new java.awt.Font("Georgia", 3, 14));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Qty               :-");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 130, 110, 20);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(120, 10, 100, 23);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(120, 40, 100, 23);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(120, 70, 100, 23);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(120, 100, 100, 23);

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 14));
        getContentPane().add(jTextField5);
        jTextField5.setBounds(120, 130, 100, 23);

        jLabel7.setFont(new java.awt.Font("Georgia", 3, 14));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Item name :-");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 40, 110, 20);

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(330, 10, 110, 23);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Georgia", 3, 14));
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 260, 90, 30);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Georgia", 3, 14));
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 190, 90, 30);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Georgia", 3, 14));
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(160, 190, 90, 30);

        jList1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(290, 40, 150, 290);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/0094.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-870, -10, 1450, 1090);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-462)/2, (screenSize.height-377)/2, 462, 377);
    }// </editor-fold>//GEN-END:initComponents
    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        try {
            Connection a = DB.createConnection();
            ResultSet r = a.createStatement().executeQuery("select * from item where itemid='" + jTextField1.getText() + "'");

            boolean b = false;
            while (r.next()) {
                b = true;
                String a1 = r.getString("itemid");
                jTextField1.setText(a1);

                String a2 = r.getString("itemname");
                jTextField2.setText(a2);

                String a3 = r.getString("pup");
                jTextField3.setText(a3);

                String a4 = r.getString("sup");
                jTextField4.setText(a4);

            }
            if (!b) {
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }


    // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
        try {
            Connection a = DB.createConnection();
            ResultSet r = a.createStatement().executeQuery("select * from item where itemid='" + jTextField6.getText() + "'");

            boolean b = false;
            while (r.next()) {
                b = true;
                String a1 = r.getString("itemid");
                jTextField1.setText(a1);

                String a2 = r.getString("itemname");
                jTextField2.setText(a2);

                String a3 = r.getString("pup");
                jTextField3.setText(a3);

                String a4 = r.getString("sup");
                jTextField4.setText(a4);

            }
            if (!b) {
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Connection a = DB.createConnection();
            int qty1 = 0;
            ResultSet r = a.createStatement().executeQuery("select qty from stock where itemid='" + jTextField1.getText() + "'");

            boolean b = false;
            while (r.next()) {
                b = true;
                qty1 = Integer.parseInt(r.getString("qty"));

            }
            int qty2 = Integer.parseInt(jTextField5.getText());
            int newqty = qty1 + qty2;

            if (b) {
                PreparedStatement p = a.prepareStatement("update stock set qty='" + newqty + "' where itemid='" + jTextField1.getText() + "'");
                p.executeUpdate();
                p.close();

                JOptionPane.showMessageDialog(null, "Successfully Updated");
                setname();
            } else {
                PreparedStatement p1 = a.prepareStatement("insert into stock values('" + jTextField1.getText() + "','" + jTextField2.getText() + "','" + jTextField3.getText() + "','" + jTextField4.getText() + "','" + jTextField5.getText() + "')");

                p1.executeUpdate();
                p1.close();

                JOptionPane.showMessageDialog(null, "Successfully Saved");
                setname();
            }
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");

        } catch (Exception e) {
            e.printStackTrace();
        }


    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            Connection a = DB.createConnection();
            PreparedStatement p = a.prepareStatement("delete from stock where itemid='" + jTextField1.getText() + "'");
            p.executeUpdate();
            p.close();

            JOptionPane.showMessageDialog(null, "Successfully Deleted");
            setname();
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            

        } catch (Exception e) {
            e.printStackTrace();
        }


    // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");

    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new stockin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
